{% set name = "booleanoperations" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/booleanOperations-{{ version }}.zip
  sha256: 8cfa821c32ad374fa120d6b2e0b444ebeac57c91e6631528645fa19ac2a281b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - wheel
  run:
    - fonttools >=4.0.2
    - pyclipper >=1.1.0.post1
    - python >={{ python_min }}

test:
  imports:
    - booleanOperations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/typemytype/booleanOperations
  summary: Boolean operations on paths.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
